# Use root/example as user/password credentials

# Before use, change <root>, <password> for credentials and <localpath> for data store
version: '3.9'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: <root>
      MONGO_INITDB_ROOT_PASSWORD: <Password>
    volumes:
      - <localpath>/data/configdb:/data/configdb
      - <localpath>/data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: <root>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <password>
      ME_CONFIG_MONGODB_URL: mongodb://<root>:<Password>@mongo:27017/
      ME_CONFIG_BASICAUTH: false